name: xai_llm
channels:
  - defaults
dependencies:
  - ca-certificates=2024.3.11
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.9.19
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tqdm=4.65.0
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - diskcache==5.6.3
      - filelock==3.13.3
      - fsspec==2024.3.1
      - huggingface-hub==0.22.2
      - idna==3.6
      - inquirerpy==0.3.4
      - jinja2==3.1.3
      - llama-cpp-python==0.2.58
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.4
      - packaging==24.0
      - pfzy==0.3.4
      - prompt-toolkit==3.0.43
      - pyyaml==6.0.1
      - requests==2.31.0
      - sympy==1.12
      - torch==2.2.2
      - typing-extensions==4.10.0
      - urllib3==2.2.1
      - wcwidth==0.2.13
